Repository Go-To-Byte/DouSheng, pull requests merged in 2023-02, with the labels that each got.

#8 docs: 📝添加基础文档
  .gitignore
  README.md
  dou_kit/README.md
  dou_kit/client/README.md
  dou_kit/client/client.go
  dou_kit/client/client_test.go
  dou_kit/cmd/README.md
  dou_kit/cmd/init.go
  dou_kit/cmd/root.go
  dou_kit/conf/README.md
  dou_kit/conf/config.go
  dou_kit/conf/config_test.go
  dou_kit/conf/consul.go
  dou_kit/conf/load.go
  dou_kit/conf/test.toml
  dou_kit/constant/README.md
  dou_kit/docs/static/micro1.png
  dou_kit/docs/static/micro2.png
  dou_kit/exception/README.md
  dou_kit/ioc/README.md
  dou_kit/protocol/README.md
  dou_kit/protocol/grpc.go
  user_center/client/README.md
  user_center/client/rpc/client.go
  user_center/client/rpc/client_test.go
  user_center/client/rpc/gin_auth.go
  user_center/etc/config.toml.template
  video_service/client/rpc/client.go
  video_service/etc/config.toml.template
  video_service/store/README.md
Labels: documentation

#20 ✅第一次APP联调 [基础接口]
  api_rooter/apps/video/api/video.go
  api_rooter/go.mod
  api_rooter/go.sum
  user_center/apps/user/pb/user.proto
  user_center/apps/user/user.pb.go
  user_center/go.mod
  user_center/go.sum
  video_service/apps/video/impl/dao.go
  video_service/apps/video/impl/video.go
  video_service/go.mod
  video_service/go.sum
Labels: enhancement

#22 📝部分文档、修改项目README
  .github/workflows/deploy-docs.yml
  .gitignore
  README.md
  guidance/docs/.vuepress/config.js
  guidance/docs/.vuepress/styles/index.styl
  guidance/docs/README.md
  guidance/docs/framework/evolve.md
  guidance/docs/framework/ioc.md
  guidance/docs/framework/lifecycle.md
  guidance/docs/handbook/feature.md
  guidance/docs/handbook/start.md
  guidance/docs/handbook/why.md
  guidance/docs/index/team.md
  guidance/docs/kit/base.md
  guidance/docs/kit/conf.md
  guidance/docs/kit/err.md
  guidance/docs/kit/grpcserver.md
  guidance/docs/kit/httpserver.md
  guidance/docs/kit/make.md
  guidance/docs/kit/proto.md
  guidance/docs/other/gowork.md
  guidance/docs/service/comment.md
  guidance/docs/service/relation.md
  guidance/docs/service/user.md
  guidance/docs/service/video.md
  guidance/package.json
  guidance/pnpm-lock.yaml
Labels: documentation

#39 🚀 fix: 修改重复点赞报错与获取点赞视频列表错误的Bug
  interaction_service/apps/favorite/app.go
  interaction_service/apps/favorite/impl/dao.go
  interaction_service/apps/favorite/impl/favorite.go
  interaction_service/apps/favorite/impl/favorite_test.go
Labels: bug

#42 🔥 feat: 新增通过视频ID获取评论总数和点赞总数的RPC接口
  interaction_service/apps/comment/app.go
  interaction_service/apps/comment/comment.pb.go
  interaction_service/apps/comment/comment_grpc.pb.go
  interaction_service/apps/comment/impl/comment.go
  interaction_service/apps/comment/impl/comment_test.go
  interaction_service/apps/comment/impl/dao.go
  interaction_service/apps/comment/pb/comment.proto
  interaction_service/apps/favorite/app.go
  interaction_service/apps/favorite/favorite.pb.go
  interaction_service/apps/favorite/favorite_grpc.pb.go
  interaction_service/apps/favorite/impl/dao.go
  interaction_service/apps/favorite/impl/favorite.go
  interaction_service/apps/favorite/impl/favorite_test.go
Labels: enhancement
